/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 62859
 */
public class TUGAS_01_UI_NabilSahsadaSurano extends javax.swing.JFrame {

    /**
     * Creates new form TUGAS_01_UI_NabilSahsadaSurano
     */
    public TUGAS_01_UI_NabilSahsadaSurano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        NamaLbl = new java.awt.Label();
        NamaLbl1 = new java.awt.Label();
        NamaLbl2 = new java.awt.Label();
        Alamat = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Kelas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        isifile = new java.awt.TextArea();
        SetSemua = new javax.swing.JButton();
        ambilFile = new javax.swing.JFileChooser();
        isi1 = new java.awt.TextArea();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulir Pendaftaran");
        getContentPane().setLayout(null);

        NamaLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NamaLbl.setName(""); // NOI18N
        NamaLbl.setText("Alamat");
        getContentPane().add(NamaLbl);
        NamaLbl.setBounds(30, 130, 40, 20);

        NamaLbl1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NamaLbl1.setName(""); // NOI18N
        NamaLbl1.setText("Nama");
        getContentPane().add(NamaLbl1);
        NamaLbl1.setBounds(30, 70, 38, 20);

        NamaLbl2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        NamaLbl2.setName(""); // NOI18N
        NamaLbl2.setText("Kelas");
        getContentPane().add(NamaLbl2);
        NamaLbl2.setBounds(30, 100, 36, 20);
        getContentPane().add(Alamat);
        Alamat.setBounds(100, 130, 410, 22);
        getContentPane().add(Nama);
        Nama.setBounds(100, 70, 410, 22);
        getContentPane().add(Kelas);
        Kelas.setBounds(100, 100, 410, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULIR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 10, 120, 22);

        isifile.setEditable(false);
        getContentPane().add(isifile);
        isifile.setBounds(590, 440, 680, 240);

        SetSemua.setText("Proses");
        SetSemua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SetSemuaMouseClicked(evt);
            }
        });
        getContentPane().add(SetSemua);
        SetSemua.setBounds(270, 180, 71, 25);

        ambilFile.setApproveButtonText("Buka");
        ambilFile.setApproveButtonToolTipText("");
        ambilFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambilFileActionPerformed(evt);
            }
        });
        getContentPane().add(ambilFile);
        ambilFile.setBounds(570, 20, 704, 397);

        isi1.setEditable(false);
        getContentPane().add(isi1);
        isi1.setBounds(60, 250, 490, 160);

        setBounds(0, 0, 1328, 755);
    }// </editor-fold>//GEN-END:initComponents

    private void SetSemuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SetSemuaMouseClicked
    String nama = Nama.getText();
    String kelas = Kelas.getText();
    String alamat = Alamat.getText();
    
    isifile.setText("Nama Kamu Adalah : "+nama+"\n"+"Kelasmu Adalah "+kelas+"\n"+"Alamatmu Dijalan "+alamat);
    }//GEN-LAST:event_SetSemuaMouseClicked

    private void ambilFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambilFileActionPerformed
       
    }//GEN-LAST:event_ambilFileActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TUGAS_01_UI_NabilSahsadaSurano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TUGAS_01_UI_NabilSahsadaSurano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TUGAS_01_UI_NabilSahsadaSurano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TUGAS_01_UI_NabilSahsadaSurano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TUGAS_01_UI_NabilSahsadaSurano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Alamat;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField Nama;
    private java.awt.Label NamaLbl;
    private java.awt.Label NamaLbl1;
    private java.awt.Label NamaLbl2;
    private javax.swing.JButton SetSemua;
    private javax.swing.JFileChooser ambilFile;
    private java.awt.TextArea isi1;
    private java.awt.TextArea isifile;
    private javax.swing.JLabel jLabel1;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
